#spring.application.name=entrastuff
#
#spring.datasource.url=jdbc:postgresql://localhost:5432/your_database
#spring.datasource.username=your_username
#spring.datasource.password=your_password
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring:
  application:
    name: entrastuff
  datasource:
    url: jdbc:postgresql://localhost:5432/entrastuff-db
    username: postgres
    password: example
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      # Use 'create' for dev, 'validate' for prod
      ddl-auto: create
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc.batch_size: 100
      order_inserts: true
