spring:
  application:
    name: entrastuff

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/entrastuff-db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:example}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      # Use 'create' for dev, 'validate' for prod
      ddl-auto: create
      dialect: org.hibernate.dialect.PostgreSQLDialect
      #jdbc.batch_size: 100
      #order_inserts: true

  devtools:
    restart:
      enabled: true

auth:
  username: ${AUTH_USERNAME}
  password: ${AUTH_PASSWORD}

entra:
  tenant-id: ${ENTRA_TENANT_ID}
  client-id: ${ENTRA_CLIENT_ID}
  client-secret: ${ENTRA_CLIENT_SECRET}