services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: entrastuff-db
    volumes:
      - pgdata:/var/lib/postgresql/data 
    ports:
      - 5432:5432
 
volumes:
  pgdata:
